name: Sync Fork with Upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Fork as Remote
        run: git remote add fork https://github.com/fa7271/FrontServer.git

      - name: Push changes to Fork
        env:
          GITHUB_USERNAME: fa7271
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push -f https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/fa7271/FrontServer.git main
